
prom-web-portal:
  enabled: true
  nameOverride: prom-web-portal

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/prom/prom-web-portal

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: http
