apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-portal-cert
spec:
  secretName: web-portal-cert
  dnsNames:
    - {{ .Values.domainWebPortalUI }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
